121 write proper readme
GiPHouse/qbaylogic-clash-based-macipudp-stack-spring24 pull request #143
Opened 2024-05-30 13:23 UTC by Daanww

Please like, review and subscribe.

2024-05-30 15:00 UTC, rowanG077 requested changes

2024-05-30 15:00 UTC, rowanG077 commented on README.md
> +# Cλash Ethernet 🙏✨
Should be `Clash`, Cλash is an old name.

2024-05-30 15:00 UTC, rowanG077 commented on README.md
> +| ICMP(echo)            | :white_check_mark: | :x:              | :white_check_mark:       |
Add `IP`

2024-05-30 15:00 UTC, rowanG077 commented on README.md
> +| **Total LUT4s** | 2768           | 3067    |         |
Only do Total LUT4 and Total DFF

2024-05-30 15:00 UTC, rowanG077 commented on README.md
> +\* Clash Ethernet and Verilog Ethernet have a full ARP table, LiteEth has only 2 registers.
Actually Liteeth does support full ARP table now. They got their shit together.

2024-05-30 15:00 UTC, rowanG077 commented on README.md
> +  the ```|>``` operator, to create a custom stack. For example:
Refer to clash protocols in general. https://github.com/clash-lang/clash-protocols You also have `|>` but also have circuit notation. So I would just say it is easy to create specialized stacks with minimal overhead. And not refer to specific implementation functions.

2024-05-31 12:15 UTC, MatthijsMu reviewed
Looks good, overall. See some minor comments.

2024-05-31 12:15 UTC, MatthijsMu commented on README.md
> +  verifyChecksum |> depacketizerC const |> verifyLength
maybe show some circuit notation with a nonlinear circuit? This is oficially a Protocols feature but it is definitely a merit of using our core

2024-05-31 12:15 UTC, MatthijsMu commented on README.md
> +  significantly more work.
what would "doing the same in Verilog or LiteEth" require me (the end user) to do then? I understand that Verilog would be long, but a snippet with some LiteEth would be useful (if not too long), or else refer to the appendix? Now I don't have a comparison.

2024-05-31 12:15 UTC, MatthijsMu commented on README.md
> +LithEth and Verilog, using a data width of 4 and a simple echo design.
4 bytes

2024-05-31 12:15 UTC, MatthijsMu commented on README.md
> +# How to use as a developer
I would include an additional paragraph on where (in `env.sh`, that is) to set up environment variables (interface name and device name). This is a step seasoned developers would understand, but which junior developers might want to get reminded about.

2024-05-31 12:18 UTC, rowanG077 commented on README.md
> +  significantly more work.
Personally I wouldn't refer at all here to the other projects. This is almost akin to mud slinging tbh which I don't really like. Simply say it's easy to do in clash and that's it.

2024-06-06 14:58 UTC, merged