76 ip loopback hardware test
GiPHouse/qbaylogic-clash-based-macipudp-stack-spring24 pull request #144
Opened 2024-05-30 14:20 UTC by Akribes

Expands the echo stack to depacketize and repacketize IP packets and adds a python test to test this. The destination mac address is still hard coded.

Also includes some bug fixes for the up converter and ip depacketizer to make this work.

2024-05-30 14:35 UTC, JLaumen reviewed
We want to provide an example stack (with usage documentation) with just MAC (which currently is Rx/TxStack.hs), so I think it's better to leave those files as is and create new modules that import and build upon those stacks.

2024-05-30 14:37 UTC, rowanG077 requested changes
One change only really. And the splitting of the stack into mac and IP in examples @JLaumen mentioned.

2024-05-30 14:37 UTC, rowanG077 commented on src/Clash/Cores/Ethernet/RxStack.hs
> +    isForMyMac myMac h = let to = _macDst h in to == myMac || to == broadcastMac
```Haskell
isForMyMac myMac (_macDst -> to) = to == myMac || to == broadcastMac
```

2024-06-01 10:10 UTC, JLaumen approved these changes

2024-06-01 10:10 UTC, JLaumen commented on src/Clash/Cores/Ethernet/Examples/RxStacks.hs
> +    isForMyMac myMac (_macDst -> to) = to == myMac || to == broadcastMac
🥺👉👈

2024-06-01 10:10 UTC, JLaumen commented on src/Clash/Cores/Ethernet/Examples/RxStacks.hs
> +  => KnownNat dataWidth
I think this was already in the original RxStack like this, but formatting the constraints half as a tuple looks a bit weird. I'd prefer something like
```haskell
ipRxStack :: forall (dataWidth :: Nat) (dom :: Domain) (domEth :: Domain)
   . HiddenCLockResetEnable dom
  => KnownDomain domEth
  => HardwareCrc Crc32_ethernet 8 dataWidth
  => 1 <= dataWidth
  => KnownNat dataWidth
```
Or format it entirely as a tuple.

2024-06-01 12:33 UTC, rowanG077 approved these changes

2024-06-01 12:41 UTC, merged